### ISSUE TITLE
Checklist disappears 

### ISSUE THREAD

**Issue by Xsinity** [mouseSpaz/spaz.gg-issues#3]
**Describe the bug**
After deleting modules from the checklist if you delete multiple modules back to back to back to back the entire checklist will freeze and you wont be able to delete anything, then after refreshing the page it will take a few mins for the checklist to pop back up. 

**Expected behavior**
Delete modules and refresh in real time and not freeze

**Comment by Sh3nl0ng** [comment]
This is a result of API throttling. The checklist feature is going to get a substantial rebuild this week.

As a short-term solution I will open the throttle more to hopefully avoid hitting the limit. 

Long-term a rebuild should focus on optimizing the update/refresh cycle so every change to the checklist doesn't result in ~3 downstream requests.

**Comment by Sh3nl0ng** [comment]
I've increased the API requests-per-minute throttle from 60 to 120.
